### ISSUE TITLE
Create-React-App testing fails

### ISSUE THREAD

**Issue by lunush** [onderonur/react-intersection-observer-hook#15]
Hi there,

I have a react component that uses your [react-infinite-scroll-hook](https://github.com/onderonur/react-infinite-scroll-hook) and couldn't get tests for it to work properly. I would always get the following error:
```
ReferenceError: IntersectionObserver is not defined
```
[Here](https://github.com/lunush/error-reproduction-react-intersection-observer-hook) is a minimal reproduction example. I also used [intersetion-observer polyfill](https://github.com/w3c/IntersectionObserver/tree/main/polyfill) as a workaround for this issue and it seems to work fine. Just toggle the first import statement in `App.js`.

By the way, when I tried testing that component with plain `@testing-library/react`, it worked just fine.

**Comment by onderonur** [comment]
Hello there 👋 

Firstly, hugely sorry for responding to this thread so late.

I didn't have any chance to look into this unfortunately. And since it looked like this issue was inactive, I didn't prioritize it afterwards.

I will close this issue since currently CRA is not the most up-to-date way of using React and there are not much activity in this issue.

Again, thanks for this issue 🙏
